FROM mcr.microsoft.com/playwright/python:v1.50.0-jammy
ENV POETRY_HOME="/opt/poetry"
ENV PATH="$POETRY_HOME/bin:$PATH"

RUN curl -sSL https://install.python-poetry.org | python3 -

WORKDIR /app


COPY pyproject.toml poetry.lock ./

RUN poetry install --no-root 

COPY . .

EXPOSE 8080

# Run the application with gunicorn
CMD ["poetry", "run", "gunicorn", "-w", "4", "-b", "0.0.0.0:8080", "--timeout", "900","app:app"]
